### PR TITLE
Fix relocation

### PR DESCRIPTION
**Pull request by hoegaarden**

### CODE REVIEW

**Review by leclaist — APPROVED** [review]
i like the timeout map :)

**Comment by hoegaarden** [comment]
> i like the timeout map :)

Well, I don't. At least not that indirection through `TimeoutMap` to `TimeoutsSingleCluster` or `TimeoutsMultiCluster`.

But I wasn't able to find a better / nicer way to do that and express different timeouts based on the combination of the values of `TanzuNetRelocateImages` and `TAPClusterArch`.

**Comment by hoegaarden** [comment]
```bash
ubuntu@ip-10-0-143-137:~$ for c in `kubectl config get-contexts -o name` ; do \
  echo "---- $c ----" ; \
  kubectl --context="$c" get node -o json | jq '[ .items[].status.images[].names | add | split("/")[0] ] | sort | unique' ; \
done
---- arn:aws:eks:us-east-1:707215255447:cluster/horlh-s-3-build ----
[
  "YYYY.dkr.ecr-fips.us-east-1.amazonaws.com",
  "YYYY.dkr.ecr.us-east-1.amazonaws.com",
  "XXXX.dkr.ecr.us-east-1.amazonaws.com",
  "docker.io",
  "public.ecr.aws",
  "registry.k8s.io"
]
---- arn:aws:eks:us-east-1:707215255447:cluster/horlh-s-3-iterate ----
[
  "YYYY.dkr.ecr-fips.us-east-1.amazonaws.com",
  "YYYY.dkr.ecr.us-east-1.amazonaws.com",
  "XXXX.dkr.ecr.us-east-1.amazonaws.com",
  "docker.io",
  "public.ecr.aws",
  "registry.k8s.io"
]
---- arn:aws:eks:us-east-1:707215255447:cluster/horlh-s-3-run ----
[
  "YYYY.dkr.ecr-fips.us-east-1.amazonaws.com",
  "YYYY.dkr.ecr.us-east-1.amazonaws.com",
  "XXXX.dkr.ecr.us-east-1.amazonaws.com",
  "public.ecr.aws",
  "registry.k8s.io"
]
---- arn:aws:eks:us-east-1:707215255447:cluster/horlh-s-3-view ----
[
  "YYYY.dkr.ecr-fips.us-east-1.amazonaws.com",
  "YYYY.dkr.ecr.us-east-1.amazonaws.com",
  "XXXX.dkr.ecr.us-east-1.amazonaws.com",
  "public.ecr.aws",
  "registry.k8s.io"
]
ubuntu@ip-10-0-143-137:~$  
```

->
- no image from the VMware registry
- there is one image from dockerhub (`docker.io/library/gradle@sha256:941f5246bbae09fec8810cdb8f8ce0d04c0196d74014f453e582e65d037ee6b9docker.io/library/gradle:latest`), probably coming in with the default supply chain

**Comment by hoegaarden** [comment]
Right now the timeouts are set up with the assumption that relocation takes 45m, ie. 45min has been added to the `CloudInit` and `TAPInstall` phases' timeouts compared to the "non-relocation" timeouts.

For me the relocation however only took ~25min, so we might want to
- monitor the durations in CI
- potentially adapt the timeouts

so that we hit a good balance between wait times for users when the stack runs into a timeout and having enough "buffer" for when relocation takes a bit longer for environmental reasons.

**Comment by hoegaarden** [comment]
Merging now, with Stephani's explicit approval, my implicit one, and the CI succeeding.

**Pull request merged**
